language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "shitoriz-github"
    token:
      secure: "fe1e271ef07ffcbe0ed835ddfd5bf31e40659776"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
